#!/usr/bin/env python3

import chess.pgn
import uuid
import argparse

from chess import Board
from datetime import date
from pos_generator import generate_kxk, generate_kqk, generate_krk
from network import load_or_create_model
from mcts import MCTS, select_root_move
from prometheus_client import start_http_server, Counter

MAX_HALFMOVES_IN_GAME = 200

def format_root_moves(root, board):
    if root.visit_count == 0:
        return None

    root_moves = []
    for key, val in root.children.items():
        prop = val.visit_count / root.visit_count
        if prop >= 1e-3:
            root_moves.append("{}:{:.3f}".format(board.san(key), prop))

    return "q={:.3f}; p=[{}]".format(
        1.0 - root.value(),
        ", ".join(root_moves))

def create_node_with_comment(node, tree, best_move, board):
    new_node = node.add_main_variation(best_move)
    new_node.comment = format_root_moves(tree, board)

    for move, subtree in tree.children.items():
        if move == best_move: continue

        if subtree.visit_count > 100 and len(subtree.children) > 1:  # arbitrary threshold
            tmp_node = node.add_variation(move)
            board.push(move)
            tmp_best_move = select_root_move(subtree, board.fullmove_number, False)
            create_node_with_comment(tmp_node, subtree, tmp_best_move, board)
            board.pop()

    return new_node

def selfplay(model, num_simulations, verbose=True, prefix=None, generator=None):
    suffix = str(uuid.uuid4())
    mcts = MCTS(model, verbose, prefix, exploration_noise=True, max_simulations=num_simulations)

    total_positions = 0

    pos_counter = Counter('positions_total', "Positions generated by selfplay")
    game_counter = Counter('games_total', 'Games played by selfplay')

    while total_positions < 1638400:

        player = "Amy Zero [{}]".format(model.name)

        game = chess.pgn.Game()
        game.headers["Event"] = "Test Game"
        game.headers["White"] = player
        game.headers["Black"] = player
        game.headers["Date"] = date.today().strftime("%Y.%m.%d")
        node = game

        if generator:
            board = generator()
            game.setup(board)
        else:
            board = Board()

        while not board.is_game_over(claim_draw = True) and board.halfmove_clock < MAX_HALFMOVES_IN_GAME:
            best_move, tree = mcts.mcts(board)

            node = create_node_with_comment(node, tree, best_move, board)

            board.push(best_move)

            if node.comment:
                total_positions += 1
                pos_counter.inc()

        game.headers["Result"] = board.result(claim_draw=True)

        with open("LearnGames-{}.pgn".format(suffix), "a") as f:
            exporter = chess.pgn.FileExporter(f)
            game.accept(exporter)

        game_counter.inc()

if __name__ == "__main__":

    parser = argparse.ArgumentParser(description="Self play.")
    parser.add_argument('--sims', type=int, help="number of simulations", default=800)
    parser.add_argument('--kqk', action='store_const', const=True, default=False, help="only play K+Q vs K games")
    parser.add_argument('--krk', action='store_const', const=True, default=False, help="only play K+R vs K games")

    args = parser.parse_args()

    start_http_server(9099)

    generator = None
    if args.kqk:
        generator = generate_kqk
    if args.krk:
        generator = generate_krk

    model = load_or_create_model("combined-model.h5")
    selfplay(model, args.sims, generator=generator)
